name: nhost_gql_links_example
description: Demonstrates usage of the nhost_gql_links package
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # Nhost packages
  nhost_gql_links:
    path: ../
