name: nhost_auth_dart
description: Dart client for Nhost Auth with email/password, passwordless, MFA, anonymous sign-in, and session management.
version: 2.6.1
homepage: https://nhost.io
repository: https://github.com/nhost/nhost-dart/tree/main/packages/nhost_auth_dart
issue_tracker: https://github.com/nhost/nhost-dart/issues

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  http_parser: ^4.0.1
  http: ^1.1.0
  logging: ^1.1.0
  meta: ^1.7.0
  #Nhost_sdk
  nhost_sdk: ^5.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
