name: nhost_functions_dart_example
description: 'nhost functions_Dart sdk example'
private: true
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # Nhost packages
  nhost_functions_dart:
    path: ../
