name: nhost_flutter_example
description: Example app demonstrating nhost_flutter P1 Flutter Experience APIs.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
  

dependencies:
  flutter:
    sdk: flutter
  nhost_flutter:
    path: ../
  cupertino_icons: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  uses-material-design: true